theme: jekyll-theme-minimal

plugins:
  - jekyll-sitemap

logo: https://avatars2.githubusercontent.com/u/2852646

title: Zhiliang Xu

description: Zhiliang Xu's Tech Blog

# SEO
google_site_verification:
bing_site_verification:

# Social
twitter:
  username: zhiliaxu
facebook:
  username: zhiliang.xu.7