theme: jekyll-theme-minimal

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

logo: https://avatars2.githubusercontent.com/u/2852646

title: Zhiliang Xu

description: Zhiliang Xu's Tech Blog
